name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild build -destination 'name=iPhone 11' -scheme 'MyColor' -workspace 'MyColor.xcworkspace'
